export const ADD_PRODUCT_TO_CART_SUCCESS = 'ADD_PRODUCT_TO_CART_SUCCESS';

export const UPDATE_USER_CART = 'UPDATE_USER_CART';

export const CLEAR_CART_SUCCESS = 'CLEAR_CART_SUCCESS';

export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS';

export const RESET_CART_SUCCESS = 'RESET_CART_SUCCESS';
