export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const CHECK_LOGIN_USER_SUCCESS = 'CHECK_LOGIN_USER_SUCCESS';
export const CHECK_LOGIN_USER_BEGIN = 'CHECK_LOGIN_USER_BEGIN';
export const CHECK_LOGIN_USER_ERROR = 'CHECK_LOGIN_USER_ERROR';

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
